### ISSUE TITLE
python_scripts requires update for 3.4 changes

### ISSUE THREAD

**Issue by WeiliangChenOIST** [CNS-OIST/STEPS_Example#16]
```
Traceback (most recent call last):
  File "diffusion.py", line 166, in <module>
    tmgeom = gen_geom()
  File "diffusion.py", line 141, in gen_geom
    tetidxs[stored] = tidx
OverflowError: Python int too large to convert to C long
```
There should be some more down the line. And possibly the notebooks as well.

**Comment by WeiliangChenOIST** [comment]
Ideally, there should be an automatic script that helps the users to adapt their scripts from older versions to 3.4, such as changing `-1` to `UNDEFINED_TET` etc

**Comment by tristan0x** [comment]
I created a small Flake8 plugin to do just that:
https://github.com/tristan0x/flake8-oist-steps

When run of STEPS_Example:
```
$ flake8 python_scripts 
python_scripts/diffusion/diffusion.py:139:13: E421 consider using steps.geom.UNKNOWN_TET constant instead of -1.
```
