### ISSUE TITLE
Diffusion.ypnb needs to be updated to deal with the changes in the Python API introduced in STEPS 3.5

### ISSUE THREAD

**Issue by cattabiani** [CNS-OIST/STEPS_Example#22]
The example:

[diffusion](https://github.com/CNS-OIST/STEPS_Example/blob/master/user_manual/source/diffusion.ipynb)

needs to be updated since the python API in STEPS 3.5 changed

[steps 3.5 changelog](https://github.com/CNS-OIST/STEPS/blob/master/RELEASES.md#python-api)

In fact, I was building the new docker image and I got this error:

```
Step 15/20 : RUN cd /var/src/user_manual  && jupyter nbconvert      --to notebook      --execute      --inplace      --ExecutePreprocessor.timeout=360      $EXAMPLE_NOTEBOOKS_TO_REBUILD
 ---> Running in 2e66a9f26c96
[NbConvertApp] Converting notebook diffusion_boundary.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
[NbConvertApp] Writing 54025 bytes to diffusion_boundary.ipynb
[NbConvertApp] Converting notebook diffusion.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
[2020-02-04 10:58:27,057][ERROR][/var/src/STEPS/src/steps/geom/tetmesh.cpp:784][std::vector<double> steps::tetmesh::Tetmesh::getTetBarycenter(steps::tetrahedron_id_t) const]: ArgErr: Tetrahedron index is out of range.
```

**Comment by tristan0x** [comment]
The error seems to come from this function call:
```python
# Fetch the barycenter of the tetrahedron:
baryc = mesh.getTetBarycenter(tetidxs[i])
```
It means at least one tetrahedron identifiers in `tetidxs` is invalid i.e not in range `[0, number of tetrahedrons[`

Before STEPS 3.5, `-1` was returned by `mesh.findTetByPoint` to indicate _unknown tetrahedron_. The value has changed in STEPS 3.5. So the test below is wrong and must be modified.
```python
# Find the tetrahedron that encompasses this point:
tidx = mesh.findTetByPoint([xcrd, ycrd, zcrd])

# -1 was returned if point is outside the mesh
if (tidx == -1): continue
```

Besides, the `tetidxs` declaration should use the `steps.geom.INDEX_DTYPE` constant (see releases notes)

**Comment by tristan0x** [comment]
Here is the development environment I would use to fix that:

1. Comment https://github.com/CNS-OIST/STEPS_Docker/blob/master/recipe/Dockerfile#L71-L77
1. Build the Docker image
1. Start the container
1. Edit the _diffusion_ notebook from Jupyterlab running inside the container

**Comment by cattabiani** [comment]
The diffusion example has been updated to address the changes in the Python API for STEPS 3.5

No other examples were affected by the change. The changes have been merged.
