### ISSUE TITLE
broken link in the 3.6 manual

### ISSUE THREAD

**Issue by WeiliangChenOIST** [CNS-OIST/STEPS_Example#25]
The  STEPS_Example repository link in https://github.com/CNS-OIST/STEPS_Example/blob/master/user_manual/source/memb_pot.ipynb points to https://github.com/CNS-OIST/STEPS_Example/blob/master/user_manual/source/HH_APprop.ipynb, which no longer exists.
May need to check if there are other broken links.

**Comment by jlallouette** [comment]
Was this link also broken in the previous manuals? I think I updated the links to the `python_scripts` directory after changing the layout there but I'll check again.

**Comment by WeiliangChenOIST** [comment]
the link changed between http://steps.sourceforge.net/old_manuals/manual_3.1.0/memb_pot.html and http://steps.sourceforge.net/old_manuals/manual_3.2.0/memb_pot.html, so yeah long ago

**Comment by WeiliangChenOIST** [comment]
Apparently, it was from me https://github.com/CNS-OIST/STEPS_Example/commit/e5b30582c78001fae61b0b4cd139f9791e59ebaa

**Comment by jlallouette** [comment]
I ran a broken link tool on the manual. It found the following broken links:


Error | URL | Anchor Text | Linked From
-- | -- | -- | --
-1 Not found: The server name or address could not be resolved | http://www.hpfem.jku.at/netgen/ | NETGEN | http://steps.sourceforge.net/manual/diffusion.html
404 Not Found | https://github.com/CNS-OIST/STEPS_Example/blob/master/user_manual/source/HH_APprop.ipynb | STEPS_Example repository | http://steps.sourceforge.net/manual/memb_pot.html
404 Not Found | https://github.com/CNS-OIST/STEPS_Example/blob/master/user_manual/source/sbml.ipynb | STEPS_Example repository | http://steps.sourceforge.net/manual/sbml_importer.html
404 Not Found | https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html | NumPy for Matlab users [301 from http://www.scipy.org/NumPy_for_Matlab_Users] [301 from https://www.scipy.org/NumPy_for_Matlab_Users] | http://steps.sourceforge.net/manual/getting_started.html
404 Not Found | https://cubit.sandia.gov/public/documentation.html | CUBIT documentation | http://steps.sourceforge.net/manual/geom_prep.html
404 Not Found | https://cubit.sandia.gov/public/14.1/help_manual/WebHelp/cubithelp.htm | CUBIT manual | http://steps.sourceforge.net/manual/geom_prep.html
-1 Not found: The host name in the certificate is invalid or does not match | https://synapses.clm.utexas.edu/anatomy/Ca1pyrmd/radiatum/K24/K24.stm | http://synapses.clm.utexas.edu/anatomy/Ca1pyrmd/radiatum/K24/K24.stm [301 from http://synapses.clm.utexas.edu/anatomy/Ca1pyrmd/radiatum/K24/K24.stm] | http://steps.sourceforge.net/manual/geom_prep.html

**Comment by jlallouette** [comment]
I will fix the ones that should point to STEPS things.

**Comment by jlallouette** [comment]
Potential replacement for the other links:
http://www.hpfem.jku.at/netgen/ -->  https://ngsolve.org/
https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html --> https://numpy.org/doc/stable/user/numpy-for-matlab-users.html
https://cubit.sandia.gov/public/documentation.html --> https://cubit.sandia.gov/documentation.html
https://cubit.sandia.gov/public/14.1/help_manual/WebHelp/cubithelp.htm --> https://cubit.sandia.gov/15.7/help_manual/WebHelp/cubithelp.htm
https://synapses.clm.utexas.edu/anatomy/Ca1pyrmd/radiatum/K24/K24.stm --> ???

**Comment by jlallouette** [comment]
I fixed all the broken links found by the tool except the last one (https://synapses.clm.utexas.edu/anatomy/Ca1pyrmd/radiatum/K24/K24.stm).

**Comment by WeiliangChenOIST** [comment]
> I fixed all the broken links found by the tool except the last one (https://synapses.clm.utexas.edu/anatomy/Ca1pyrmd/radiatum/K24/K24.stm).

the surface mesh is no longer shared by the Harris lab. We can replace it with the original imaging data.

https://synapseweb.clm.utexas.edu/sites/default/files/synapseweb/files/k24.zip

or the reference itself
https://synapseweb.clm.utexas.edu/1989harris

**Comment by iahepburn** [comment]
Thanks Jules. Think that K24 one has moved here: https://synapseweb.clm.utexas.edu/sites/default/files/synapseweb/files/k24.zip

**Comment by iahepburn** [comment]
ah, snap

**Comment by jlallouette** [comment]
Thanks :)
