### ISSUE TITLE
Broken links to example files

### ISSUE THREAD

**Issue by WeiliangChenOIST** [CNS-OIST/STEPS_Example#5]
@FrancescoCasalegno at the moment the links to examples in the user manual source files are broken as we change the directory from https://github.com/CNS-OIST/STEPS_Example/tree/master/manual_tutorials/ to https://github.com/CNS-OIST/STEPS_Example/tree/master/python_scripts. For example, the one in https://github.com/CNS-OIST/STEPS_Example/blob/master/user_manual/source/well_mixed.ipynb.

For the ones have only Python script we can just replace the links directly, but for the ones that have both python script and jupyter notebooks, do you think it is better to give the notebook link or give both?

**Comment by FrancescoCasalegno** [comment]
@WeiliangChenOIST if we mention another manual chapter (e.g. well mixed) I believe we can only put the Jupyter notebook link.

**Comment by WeiliangChenOIST** [comment]
links fixed.
